CUDA_VISIBLE_DEVICES=0 python run_src/do_generate.py \
    --dataset_name MBPP \
    --test_json_filename test_one \
    --api gpt3.5-turbo \
    --model_ckpt gpt-3.5-turbo \
    --note default \
    --num_rollouts 1 \
    --verbose \
    --save_tree \
    --max_depth_allowed 6 \
    --run_outputs_root test_outputs 